services:
  redis:
    image: redis:alpine
    container_name: gotrain-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  gotrain-archiver:
    image: rijdendetreinen/gotrain
    container_name: gotrain-archiver
    command: ["/app/gotrain", "archiver", "--config", "/app/config/config.yaml"]
    environment:
      - SOURCE_SERVER=tcp://pubsub.besteffort.ndovloket.nl:7664
      - SOURCE_ENVELOPES_ARRIVALS=/RIG/InfoPlusDASInterface4
      - SOURCE_ENVELOPES_DEPARTURES=/RIG/InfoPlusDVSInterface4
      - SOURCE_ENVELOPES_SERVICES=/RIG/InfoPlusRITInterface2
    volumes:
      - ./config/GoTrain.yaml:/app/config/config.yaml
    depends_on:
      - redis
    restart: unless-stopped

  data-interpreter:
    build:
      context: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - gotrain-archiver
    restart: unless-stopped